//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AntiCheat.Lang {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class en_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal en_US() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AntiCheat.Lang.en_US", typeof(en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Detects when a player attempts to force the Company monster to attack. 的本地化字符串。
        /// </summary>
        internal static string config_Boss {
            get {
                return ResourceManager.GetString("config_Boss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Detects players routing moon from priced to free 的本地化字符串。
        /// </summary>
        internal static string config_ChangToFreeMoon {
            get {
                return ResourceManager.GetString("config_ChangToFreeMoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Detects when a player attempts to spoof their name as another player&apos;s. 的本地化字符串。
        /// </summary>
        internal static string config_ChatReal {
            get {
                return ResourceManager.GetString("config_ChatReal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Chat speed limit (milliseconds) 的本地化字符串。
        /// </summary>
        internal static string config_ChatReal_Cooldown {
            get {
                return ResourceManager.GetString("config_ChatReal_Cooldown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Detects when items are unusually destroyed or deleted. 的本地化字符串。
        /// </summary>
        internal static string config_DespawnItem {
            get {
                return ResourceManager.GetString("config_DespawnItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Detect the message display type, PublicChat = show in room public chat, HostChat = show in chat only host, GUI = show in GUI interface 的本地化字符串。
        /// </summary>
        internal static string config_DetectedMessageType {
            get {
                return ResourceManager.GetString("config_DetectedMessageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Detects when a monster behaves abnormally. 的本地化字符串。
        /// </summary>
        internal static string config_Enemy {
            get {
                return ResourceManager.GetString("config_Enemy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Detects players ordering items without spending credits. 的本地化字符串。
        /// </summary>
        internal static string config_FreeBuy {
            get {
                return ResourceManager.GetString("config_FreeBuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Detects players having abnormal gift box interactions. 的本地化字符串。
        /// </summary>
        internal static string config_Gift {
            get {
                return ResourceManager.GetString("config_Gift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Detects picking up items outside of default grab range. 的本地化字符串。
        /// </summary>
        internal static string config_GrabObject {
            get {
                return ResourceManager.GetString("config_GrabObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disables players from picking up scrap with belt bags 的本地化字符串。
        /// </summary>
        internal static string config_GrabObject_BeltBag {
            get {
                return ResourceManager.GetString("config_GrabObject_BeltBag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Prevents players from picking up more than 4 items 的本地化字符串。
        /// </summary>
        internal static string config_GrabObject_MoreSlot {
            get {
                return ResourceManager.GetString("config_GrabObject_MoreSlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Prevents players from picking up multiple two-handed items at the same time 的本地化字符串。
        /// </summary>
        internal static string config_GrabObject_TwoHand {
            get {
                return ResourceManager.GetString("config_GrabObject_TwoHand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Detects players using negative damage to recover health 的本地化字符串。
        /// </summary>
        internal static string config_Health_Recover {
            get {
                return ResourceManager.GetString("config_Health_Recover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ignore client configuration differences (this will mitigate the case of client errors) 的本地化字符串。
        /// </summary>
        internal static string config_IgnoreClientConfig {
            get {
                return ResourceManager.GetString("config_IgnoreClientConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Detects when a player has infinite ammo. Note: If a shotgun has already been given infinite ammo, a normal player using it may cause them to be detected as using infinite ammo as well. 的本地化字符串。
        /// </summary>
        internal static string config_InfiniteAmmo {
            get {
                return ResourceManager.GetString("config_InfiniteAmmo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Detects invisible players. 的本地化字符串。
        /// </summary>
        internal static string config_Invisibility {
            get {
                return ResourceManager.GetString("config_Invisibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Detects when a player uses an item faster than they should. 的本地化字符串。
        /// </summary>
        internal static string config_ItemCooldown {
            get {
                return ResourceManager.GetString("config_ItemCooldown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Detects when a player forces a jetpack explosion. 的本地化字符串。
        /// </summary>
        internal static string config_Jetpack {
            get {
                return ResourceManager.GetString("config_Jetpack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Kick player when this behavior is detected. 的本地化字符串。
        /// </summary>
        internal static string config_Kick {
            get {
                return ResourceManager.GetString("config_Kick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Detects when an enemy is instantly killed. 的本地化字符串。
        /// </summary>
        internal static string config_KillEnemy {
            get {
                return ResourceManager.GetString("config_KillEnemy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Detects when a player abnormally detonates a landmine. 的本地化字符串。
        /// </summary>
        internal static string config_Landmine {
            get {
                return ResourceManager.GetString("config_Landmine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show logs. 的本地化字符串。
        /// </summary>
        internal static string config_Log {
            get {
                return ResourceManager.GetString("config_Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Detects the use of mini-map mods. 的本地化字符串。
        /// </summary>
        internal static string config_Map {
            get {
                return ResourceManager.GetString("config_Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Detects when masked enemies are spawned abnormally. 的本地化字符串。
        /// </summary>
        internal static string config_Mask {
            get {
                return ResourceManager.GetString("config_Mask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Detects invalid or anomalous player names such as Nameless or Unknown. 的本地化字符串。
        /// </summary>
        internal static string config_Nameless {
            get {
                return ResourceManager.GetString("config_Nameless", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Client-side player action logs 的本地化字符串。
        /// </summary>
        internal static string config_OperationLog {
            get {
                return ResourceManager.GetString("config_OperationLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Detecting abnormal player carry weight 的本地化字符串。
        /// </summary>
        internal static string config_PlayerCarryWeight {
            get {
                return ResourceManager.GetString("config_PlayerCarryWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Restore Player Carry Weight 的本地化字符串。
        /// </summary>
        internal static string config_PlayerCarryWeight2 {
            get {
                return ResourceManager.GetString("config_PlayerCarryWeight2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Puts text in square brackets before the lobby name, leave empty to disable. 的本地化字符串。
        /// </summary>
        internal static string config_Prefix {
            get {
                return ResourceManager.GetString("config_Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Detects when a player uses the terminal remotely. 的本地化字符串。
        /// </summary>
        internal static string config_RemoteTerminal {
            get {
                return ResourceManager.GetString("config_RemoteTerminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RPC report detection delay, detect whether the player reports RPC after this time (in milliseconds) 的本地化字符串。
        /// </summary>
        internal static string config_RPCReport_Delay {
            get {
                return ResourceManager.GetString("config_RPCReport_Delay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hit RPC reporting detection, when the player is attacked and does not report blood loss, it will be detected (invincibility detection) 的本地化字符串。
        /// </summary>
        internal static string config_RPCReport_Hit {
            get {
                return ResourceManager.GetString("config_RPCReport_Hit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 KillPlayer RPC report detection, when a player is killed but does not report death, it will be detected (invincibility detection) 的本地化字符串。
        /// </summary>
        internal static string config_RPCReport_KillPlayer {
            get {
                return ResourceManager.GetString("config_RPCReport_KillPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Detects the abnormal placement of furniture. 的本地化字符串。
        /// </summary>
        internal static string config_ShipBuild {
            get {
                return ResourceManager.GetString("config_ShipBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clients can only pull the lever when this player count is reached. (StartGameOnlyHost must be set to false.) 的本地化字符串。
        /// </summary>
        internal static string config_ShipConfig2 {
            get {
                return ResourceManager.GetString("config_ShipConfig2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clients can take off after this in-game time. 的本地化字符串。
        /// </summary>
        internal static string config_ShipConfig3 {
            get {
                return ResourceManager.GetString("config_ShipConfig3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clients can take off when the number of living players in the ship is equal or greater than the specified percentage. (0-100%) 的本地化字符串。
        /// </summary>
        internal static string config_ShipConfig4 {
            get {
                return ResourceManager.GetString("config_ShipConfig4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Detects when a player attempts to force the ship lever. Kicks the player if detected. 的本地化字符串。
        /// </summary>
        internal static string config_ShipConfig5 {
            get {
                return ResourceManager.GetString("config_ShipConfig5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Allow your single vote to instantly force the autopilot as host. 的本地化字符串。
        /// </summary>
        internal static string config_ShipConfig6 {
            get {
                return ResourceManager.GetString("config_ShipConfig6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Detects when a player switches the lights too fast. 的本地化字符串。
        /// </summary>
        internal static string config_ShipLight {
            get {
                return ResourceManager.GetString("config_ShipLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Only the host may land the ship. 的本地化字符串。
        /// </summary>
        internal static string config_ShipSetting {
            get {
                return ResourceManager.GetString("config_ShipSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Detects the spam of terminal noise. 的本地化字符串。
        /// </summary>
        internal static string config_ShipTerminal {
            get {
                return ResourceManager.GetString("config_ShipTerminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Detects unusual shovel damage. 的本地化字符串。
        /// </summary>
        internal static string config_Shovel {
            get {
                return ResourceManager.GetString("config_Shovel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Allow players to deal damage without a weapon. Note that network de-sync may result in other players&apos; active inventory slots being desynchronized. 的本地化字符串。
        /// </summary>
        internal static string config_Shovel2 {
            get {
                return ResourceManager.GetString("config_Shovel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Detects when a player tries to spawn spiderwebs. 的本地化字符串。
        /// </summary>
        internal static string config_SpawnWebTrap {
            get {
                return ResourceManager.GetString("config_SpawnWebTrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Detects when a player forces a turret to go berserk. 的本地化字符串。
        /// </summary>
        internal static string config_Turret {
            get {
                return ResourceManager.GetString("config_Turret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Kitchen knife 的本地化字符串。
        /// </summary>
        internal static string Item_Knife {
            get {
                return ResourceManager.GetString("Item_Knife", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 shotgun 的本地化字符串。
        /// </summary>
        internal static string Item_Shotgun {
            get {
                return ResourceManager.GetString("Item_Shotgun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 shovel 的本地化字符串。
        /// </summary>
        internal static string Item_Shovel {
            get {
                return ResourceManager.GetString("Item_Shovel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AntiCheat mod is loaded! 的本地化字符串。
        /// </summary>
        internal static string log_load {
            get {
                return ResourceManager.GetString("log_load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {steamId} attempted to connect to the game but was rejected! (Already kicked) 的本地化字符串。
        /// </summary>
        internal static string log_refuse_connect {
            get {
                return ResourceManager.GetString("log_refuse_connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;color=red&gt;{Prefix} {msg}&lt;/color&gt; 的本地化字符串。
        /// </summary>
        internal static string MessageFormat {
            get {
                return ResourceManager.GetString("MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;color=yellow&gt;[{player}] &lt;color=red&gt;was left behind.&lt;/color&gt;&lt;/color&gt; 的本地化字符串。
        /// </summary>
        internal static string msg_behind_player {
            get {
                return ResourceManager.GetString("msg_behind_player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {player} detected attempting to force the company monster to attack! 的本地化字符串。
        /// </summary>
        internal static string msg_Boss {
            get {
                return ResourceManager.GetString("msg_Boss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {player} was detected Changes paid moon to free moon! (This behavior is only allowed for homeowners!) 的本地化字符串。
        /// </summary>
        internal static string msg_ChangeLevel {
            get {
                return ResourceManager.GetString("msg_ChangeLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {player} was detected routing moon from priced to free! 的本地化字符串。
        /// </summary>
        internal static string msg_ChangeToFreeLevel {
            get {
                return ResourceManager.GetString("msg_ChangeToFreeLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {player} tried to spoof {player2}&apos;s name in chat! 的本地化字符串。
        /// </summary>
        internal static string msg_ChatReal {
            get {
                return ResourceManager.GetString("msg_ChatReal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {player} was detected destroying items! 的本地化字符串。
        /// </summary>
        internal static string msg_DespawnItem {
            get {
                return ResourceManager.GetString("msg_DespawnItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {player} was detected trying to alter a monster&apos;s behavior! 的本地化字符串。
        /// </summary>
        internal static string msg_Enemy_ChangeOwnershipOfEnemy {
            get {
                return ResourceManager.GetString("msg_Enemy_ChangeOwnershipOfEnemy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {player} was detected trying to alter a monster&apos;s state! 的本地化字符串。
        /// </summary>
        internal static string msg_Enemy_SwitchToBehaviour {
            get {
                return ResourceManager.GetString("msg_Enemy_SwitchToBehaviour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {player} was detected buying an item for free! 的本地化字符串。
        /// </summary>
        internal static string msg_FreeBuy_Item {
            get {
                return ResourceManager.GetString("msg_FreeBuy_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {player} was detected routing to a priced moon for free! 的本地化字符串。
        /// </summary>
        internal static string msg_FreeBuy_Level {
            get {
                return ResourceManager.GetString("msg_FreeBuy_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {player} was deteccted modifying the ship&apos;s credits! ({Money})! 的本地化字符串。
        /// </summary>
        internal static string msg_FreeBuy_SetMoney {
            get {
                return ResourceManager.GetString("msg_FreeBuy_SetMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {player} was detected buying a ship unlockable for free! 的本地化字符串。
        /// </summary>
        internal static string msg_FreeBuy_unlockable {
            get {
                return ResourceManager.GetString("msg_FreeBuy_unlockable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;color=green&gt;Anti-Cheat (v{ver}) is enabled in this lobby&lt;/color&gt; 的本地化字符串。
        /// </summary>
        internal static string msg_game_start {
            get {
                return ResourceManager.GetString("msg_game_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {player} was detected causing a gift box to behave abnormally! 的本地化字符串。
        /// </summary>
        internal static string msg_Gift {
            get {
                return ResourceManager.GetString("msg_Gift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {player} was detected grabbing objects from too far away! (Player coordinates: {player_position}|Item coordinates: {object_position}) 的本地化字符串。
        /// </summary>
        internal static string msg_GrabObject {
            get {
                return ResourceManager.GetString("msg_GrabObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {player} was detected recovering health ({hp})! 的本地化字符串。
        /// </summary>
        internal static string msg_Health_Recover {
            get {
                return ResourceManager.GetString("msg_Health_Recover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {player} was detected using infinite ammo! 的本地化字符串。
        /// </summary>
        internal static string msg_InfiniteAmmo {
            get {
                return ResourceManager.GetString("msg_InfiniteAmmo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {player} was detected to be invisible! (Player coordinates: {player_position}) 的本地化字符串。
        /// </summary>
        internal static string msg_Invisibility {
            get {
                return ResourceManager.GetString("msg_Invisibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {player} was detected using an item faster than its cooldown would allow! 的本地化字符串。
        /// </summary>
        internal static string msg_ItemCooldown {
            get {
                return ResourceManager.GetString("msg_ItemCooldown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {player} was detected forcing a jetpack explosion! 的本地化字符串。
        /// </summary>
        internal static string msg_Jetpack {
            get {
                return ResourceManager.GetString("msg_Jetpack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {player} was kicked! 的本地化字符串。
        /// </summary>
        internal static string msg_Kick {
            get {
                return ResourceManager.GetString("msg_Kick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cheating detected 的本地化字符串。
        /// </summary>
        internal static string msg_KickPlayer {
            get {
                return ResourceManager.GetString("msg_KickPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {player} was detected killing a monster instantly! ({enemyName}, monster HP before: {HP}) 的本地化字符串。
        /// </summary>
        internal static string msg_KillEnemy {
            get {
                return ResourceManager.GetString("msg_KillEnemy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {player} was detected forcing a landmine explosion! 的本地化字符串。
        /// </summary>
        internal static string msg_Landmine {
            get {
                return ResourceManager.GetString("msg_Landmine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {player} was detected to have a mini-map mod! 的本地化字符串。
        /// </summary>
        internal static string msg_Map {
            get {
                return ResourceManager.GetString("msg_Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {player} was detected to have spawned Masked enemies abnormally! 的本地化字符串。
        /// </summary>
        internal static string msg_Mask {
            get {
                return ResourceManager.GetString("msg_Mask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {player} was detected to have an anomalous or invalid name! 的本地化字符串。
        /// </summary>
        internal static string msg_Nameless {
            get {
                return ResourceManager.GetString("msg_Nameless", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {player} was detected abnormal carry weight! 的本地化字符串。
        /// </summary>
        internal static string msg_PlayerCarryWeight {
            get {
                return ResourceManager.GetString("msg_PlayerCarryWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Carry Weights have been forcibly restored! 的本地化字符串。
        /// </summary>
        internal static string msg_PlayerCarryWeight_Recovery {
            get {
                return ResourceManager.GetString("msg_PlayerCarryWeight_Recovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {player} was detected using the terminal remotely! 的本地化字符串。
        /// </summary>
        internal static string msg_RemoteTerminal {
            get {
                return ResourceManager.GetString("msg_RemoteTerminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {player} was detected not report {RPC} RPC! 的本地化字符串。
        /// </summary>
        internal static string msg_RPCReport {
            get {
                return ResourceManager.GetString("msg_RPCReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {player} was detected placing furniture in an abnormal position! ({position}) 的本地化字符串。
        /// </summary>
        internal static string msg_ShipBuild {
            get {
                return ResourceManager.GetString("msg_ShipBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {player}, please wait until the number of people in the ship has reached {cfg} or more before pulling the lever, thanks! 的本地化字符串。
        /// </summary>
        internal static string msg_ShipConfig2 {
            get {
                return ResourceManager.GetString("msg_ShipConfig2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {player}, please wait until the number of people in the ship has reached {player_count}({cfg4}%) and the time has reached {cfg3} to depart. (current time: {game_time}) 的本地化字符串。
        /// </summary>
        internal static string msg_ShipConfig4 {
            get {
                return ResourceManager.GetString("msg_ShipConfig4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {player} was detected attempting to force the ship&apos;s lever! 的本地化字符串。
        /// </summary>
        internal static string msg_ShipConfig5 {
            get {
                return ResourceManager.GetString("msg_ShipConfig5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {player} was detected switching the lights too fast! 的本地化字符串。
        /// </summary>
        internal static string msg_ShipLight {
            get {
                return ResourceManager.GetString("msg_ShipLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {player} was detected making too much terminal noise! 的本地化字符串。
        /// </summary>
        internal static string msg_ShipTerminal {
            get {
                return ResourceManager.GetString("msg_ShipTerminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {player} was detected dealing abnormal damage to {player2} with a {item}! ({damageAmount}) 的本地化字符串。
        /// </summary>
        internal static string msg_Shovel {
            get {
                return ResourceManager.GetString("msg_Shovel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {player} was detected with abnormal shovel range, and damaged {player2}! ({damageAmount}) 的本地化字符串。
        /// </summary>
        internal static string msg_Shovel2 {
            get {
                return ResourceManager.GetString("msg_Shovel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {player} was detected damaging {player2} with no weapon! ({damageAmount}) 的本地化字符串。
        /// </summary>
        internal static string msg_Shovel3 {
            get {
                return ResourceManager.GetString("msg_Shovel3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {player} was detected dealing abnormal damage to {enemyName} with a {item}! ({damageAmount}) 的本地化字符串。
        /// </summary>
        internal static string msg_Shovel4 {
            get {
                return ResourceManager.GetString("msg_Shovel4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {player} was detected with abnormal shovel range, and damaged {enemyName}! ({damageAmount}) 的本地化字符串。
        /// </summary>
        internal static string msg_Shovel5 {
            get {
                return ResourceManager.GetString("msg_Shovel5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {player} was detected damaging [enemyName} with no weapon! ({damageAmount}) 的本地化字符串。
        /// </summary>
        internal static string msg_Shovel6 {
            get {
                return ResourceManager.GetString("msg_Shovel6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [{player}] sent new creature data to the terminal! ({enemy}) 的本地化字符串。
        /// </summary>
        internal static string msg_snc_player {
            get {
                return ResourceManager.GetString("msg_snc_player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {player} was detected causing a turret to go berserk! (distance: {Distance}) 的本地化字符串。
        /// </summary>
        internal static string msg_Turret {
            get {
                return ResourceManager.GetString("msg_Turret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {player} was detected causing a turret to go berserk without a weapon! 的本地化字符串。
        /// </summary>
        internal static string msg_Turret2 {
            get {
                return ResourceManager.GetString("msg_Turret2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You are the host, your vote can force the autopilot. 的本地化字符串。
        /// </summary>
        internal static string msg_vote {
            get {
                return ResourceManager.GetString("msg_vote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {player} voted for the ship to leave early. ({now}/{max}) 的本地化字符串。
        /// </summary>
        internal static string msg_vote_player {
            get {
                return ResourceManager.GetString("msg_vote_player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;color=green&gt;&lt;color=yellow&gt;[{player}]&lt;/color&gt; joined the ship.&lt;/color&gt; 的本地化字符串。
        /// </summary>
        internal static string msg_wlc_player {
            get {
                return ResourceManager.GetString("msg_wlc_player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ActionLog] {player} purchased {items} 的本地化字符串。
        /// </summary>
        internal static string OperationLog_BuyItem {
            get {
                return ResourceManager.GetString("OperationLog_BuyItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ActionLog] {player} purchased {unlockable} 的本地化字符串。
        /// </summary>
        internal static string OperationLog_BuyShipUnlockable {
            get {
                return ResourceManager.GetString("OperationLog_BuyShipUnlockable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ActionLog] {player} routed to moon {planet} 的本地化字符串。
        /// </summary>
        internal static string OperationLog_ChangeLevel {
            get {
                return ResourceManager.GetString("OperationLog_ChangeLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {player} is joining... 的本地化字符串。
        /// </summary>
        internal static string OperationLog_JoinLobby {
            get {
                return ResourceManager.GetString("OperationLog_JoinLobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [AntiCheat] 的本地化字符串。
        /// </summary>
        internal static string Prefix {
            get {
                return ResourceManager.GetString("Prefix", resourceCulture);
            }
        }
    }
}
