//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AntiCheat.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class en_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal en_US() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AntiCheat.Lang.en_US", typeof(en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summon Boss Detection.
        /// </summary>
        internal static string config_Boss {
            get {
                return ResourceManager.GetString("config_Boss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speech forgery detection.
        /// </summary>
        internal static string config_ChatReal {
            get {
                return ResourceManager.GetString("config_ChatReal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destroyed item detection.
        /// </summary>
        internal static string config_DespawnItem {
            get {
                return ResourceManager.GetString("config_DespawnItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monster anomaly detection.
        /// </summary>
        internal static string config_Enemy {
            get {
                return ResourceManager.GetString("config_Enemy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free purchases.
        /// </summary>
        internal static string config_FreeBuy {
            get {
                return ResourceManager.GetString("config_FreeBuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gift box detection.
        /// </summary>
        internal static string config_Gift {
            get {
                return ResourceManager.GetString("config_Gift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grabbed object detection.
        /// </summary>
        internal static string config_GrabObject {
            get {
                return ResourceManager.GetString("config_GrabObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infinite bullet detection.
        /// </summary>
        internal static string config_InfiniteAmmo {
            get {
                return ResourceManager.GetString("config_InfiniteAmmo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stealth detection.
        /// </summary>
        internal static string config_Invisibility {
            get {
                return ResourceManager.GetString("config_Invisibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item usage cooldown detection.
        /// </summary>
        internal static string config_ItemCooldown {
            get {
                return ResourceManager.GetString("config_ItemCooldown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jetpack explosion detection.
        /// </summary>
        internal static string config_Jetpack {
            get {
                return ResourceManager.GetString("config_Jetpack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kick player when this behavior is detected.
        /// </summary>
        internal static string config_Kick {
            get {
                return ResourceManager.GetString("config_Kick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kill enemy detection.
        /// </summary>
        internal static string config_KillEnemy {
            get {
                return ResourceManager.GetString("config_KillEnemy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explosive mine detection.
        /// </summary>
        internal static string config_Landmine {
            get {
                return ResourceManager.GetString("config_Landmine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimap detection.
        /// </summary>
        internal static string config_Map {
            get {
                return ResourceManager.GetString("config_Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Masked enemy detection.
        /// </summary>
        internal static string config_Mask {
            get {
                return ResourceManager.GetString("config_Mask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player name detection (Nameless or Unknown).
        /// </summary>
        internal static string config_Nameless {
            get {
                return ResourceManager.GetString("config_Nameless", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spacecraft item location anomaly detection.
        /// </summary>
        internal static string config_ShipBuild {
            get {
                return ResourceManager.GetString("config_ShipBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-hosts can only log in if more than the specified number of people (host permissions need to be turned off).
        /// </summary>
        internal static string config_ShipConfig2 {
            get {
                return ResourceManager.GetString("config_ShipConfig2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-homeowners can only take off after this time.
        /// </summary>
        internal static string config_ShipConfig3 {
            get {
                return ResourceManager.GetString("config_ShipConfig3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-homeowners can only take off when the number of people in the spaceship (survival) exceeds the above ratio (0-100%).
        /// </summary>
        internal static string config_ShipConfig4 {
            get {
                return ResourceManager.GetString("config_ShipConfig4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detect force lever behavior (kick player when this behavior is detected).
        /// </summary>
        internal static string config_ShipConfig5 {
            get {
                return ResourceManager.GetString("config_ShipConfig5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votes must exceed the above ratio to take off (0-100%).
        /// </summary>
        internal static string config_ShipConfig6 {
            get {
                return ResourceManager.GetString("config_ShipConfig6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lights off show detection.
        /// </summary>
        internal static string config_ShipLight {
            get {
                return ResourceManager.GetString("config_ShipLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only the host has landing rights.
        /// </summary>
        internal static string config_ShipSetting {
            get {
                return ResourceManager.GetString("config_ShipSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminal noise detection.
        /// </summary>
        internal static string config_ShipTerminal {
            get {
                return ResourceManager.GetString("config_ShipTerminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shovel damage detection.
        /// </summary>
        internal static string config_Shovel {
            get {
                return ResourceManager.GetString("config_Shovel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spider web detection.
        /// </summary>
        internal static string config_SpawnWebTrap {
            get {
                return ResourceManager.GetString("config_SpawnWebTrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enraged machine gun detection.
        /// </summary>
        internal static string config_Turret {
            get {
                return ResourceManager.GetString("config_Turret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shotgun.
        /// </summary>
        internal static string Item_Shotgun {
            get {
                return ResourceManager.GetString("Item_Shotgun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shovel.
        /// </summary>
        internal static string Item_Shovel {
            get {
                return ResourceManager.GetString("Item_Shovel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {steamId}&apos;s attempt to reconnect to the game was rejected (because he has been kicked out)!.
        /// </summary>
        internal static string log_refuse_connect {
            get {
                return ResourceManager.GetString("log_refuse_connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;color=red&gt;{Prefix} {msg}&lt;/color&gt;.
        /// </summary>
        internal static string MessageFormat {
            get {
                return ResourceManager.GetString("MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;color=yellow&gt;[{player}] &lt;color=red&gt;I haven’t boarded the ship yet...&lt;/color&gt;&lt;/color&gt;.
        /// </summary>
        internal static string msg_behind_plaer {
            get {
                return ResourceManager.GetString("msg_behind_plaer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player {player} detected summoning boss!.
        /// </summary>
        internal static string msg_Boss {
            get {
                return ResourceManager.GetString("msg_Boss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detected player {player} trying to speak as {player2}!.
        /// </summary>
        internal static string msg_ChatReal {
            get {
                return ResourceManager.GetString("msg_ChatReal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player {player} destroying item detected!.
        /// </summary>
        internal static string msg_DespawnItem {
            get {
                return ResourceManager.GetString("msg_DespawnItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player {player} detected to force change of monster hatred!.
        /// </summary>
        internal static string msg_Enemy_ChangeOwnershipOfEnemy {
            get {
                return ResourceManager.GetString("msg_Enemy_ChangeOwnershipOfEnemy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player {player} detected for grinding money!.
        /// </summary>
        internal static string msg_FreeBuy_GiveMoney {
            get {
                return ResourceManager.GetString("msg_FreeBuy_GiveMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force purchase of item detected by player {player}!.
        /// </summary>
        internal static string msg_FreeBuy_Item {
            get {
                return ResourceManager.GetString("msg_FreeBuy_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player {player} detected to force ship decoration to be unlocked!.
        /// </summary>
        internal static string msg_FreeBuy_unlockable {
            get {
                return ResourceManager.GetString("msg_FreeBuy_unlockable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;color=green&gt;Anti-cheating (v{ver}) is enabled in this room&lt;/color&gt;.
        /// </summary>
        internal static string msg_game_start {
            get {
                return ResourceManager.GetString("msg_game_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player {player} detected gift box farming!.
        /// </summary>
        internal static string msg_Gift {
            get {
                return ResourceManager.GetString("msg_Gift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player {player} detected taking objects from the air! (Player coordinates: {player_postion}|Item coordinates: {object_postion}).
        /// </summary>
        internal static string msg_GrabObject {
            get {
                return ResourceManager.GetString("msg_GrabObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player {player} detected Enable unlimited bullets!.
        /// </summary>
        internal static string msg_InfiniteAmmo {
            get {
                return ResourceManager.GetString("msg_InfiniteAmmo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abnormal coordinates of player {player} detected! (Player coordinates: {player_postion}).
        /// </summary>
        internal static string msg_Invisibility {
            get {
                return ResourceManager.GetString("msg_Invisibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An abnormal frequency of usage of {item} by player {player} was detected!.
        /// </summary>
        internal static string msg_ItemCooldown {
            get {
                return ResourceManager.GetString("msg_ItemCooldown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player {player} detonated jetpack detected!.
        /// </summary>
        internal static string msg_Jetpack {
            get {
                return ResourceManager.GetString("msg_Jetpack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {player} was kicked out of the game!.
        /// </summary>
        internal static string msg_Kick {
            get {
                return ResourceManager.GetString("msg_Kick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player {player} is detected and instantly kills the monster! ({enemyName}, remaining blood volume: {HP}).
        /// </summary>
        internal static string msg_KillEnemy {
            get {
                return ResourceManager.GetString("msg_KillEnemy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player {player} detected and forced to detonate a mine!.
        /// </summary>
        internal static string msg_Landmine {
            get {
                return ResourceManager.GetString("msg_Landmine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player {player} detected using minimap!.
        /// </summary>
        internal static string msg_Map {
            get {
                return ResourceManager.GetString("msg_Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player {player} detected as a fake!.
        /// </summary>
        internal static string msg_Mask {
            get {
                return ResourceManager.GetString("msg_Mask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An abnormality in player name has been detected!.
        /// </summary>
        internal static string msg_Nameless {
            get {
                return ResourceManager.GetString("msg_Nameless", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It was detected that player {player} placed the ship items in an abnormal position ({postion})!.
        /// </summary>
        internal static string msg_ShipBuild {
            get {
                return ResourceManager.GetString("msg_ShipBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {player} Please wait until the number of people in the spaceship reaches {cfg} or more before pulling the lever!.
        /// </summary>
        internal static string msg_ShipConfig2 {
            get {
                return ResourceManager.GetString("msg_ShipConfig2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {player} Please wait until the number of people in the spaceship reaches {player_count}({cfg4}%) and the game time takes off after {cfg3} (current time: {game_time}).
        /// </summary>
        internal static string msg_ShipConfig4 {
            get {
                return ResourceManager.GetString("msg_ShipConfig4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player {player} forced lever detected!.
        /// </summary>
        internal static string msg_ShipConfig5 {
            get {
                return ResourceManager.GetString("msg_ShipConfig5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequent use of lights by player {player} detected!.
        /// </summary>
        internal static string msg_ShipLight {
            get {
                return ResourceManager.GetString("msg_ShipLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detected that player {player} is making frequent noise!.
        /// </summary>
        internal static string msg_ShipTerminal {
            get {
                return ResourceManager.GetString("msg_ShipTerminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detected player {player} using a shovel to cause abnormal damage to player {player2}! ({damageAmount}).
        /// </summary>
        internal static string msg_Shovel {
            get {
                return ResourceManager.GetString("msg_Shovel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An abnormality in the shovel range of player {player} was detected, causing damage to player {player2}! ({damageAmount}).
        /// </summary>
        internal static string msg_Shovel2 {
            get {
                return ResourceManager.GetString("msg_Shovel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detected player {player} using his bare hands to cause damage to player {player2}! ({damageAmount}).
        /// </summary>
        internal static string msg_Shovel3 {
            get {
                return ResourceManager.GetString("msg_Shovel3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detected player {player} using a shovel to cause abnormal damage to enemy {enemyName}! ({damageAmount}).
        /// </summary>
        internal static string msg_Shovel4 {
            get {
                return ResourceManager.GetString("msg_Shovel4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An abnormality in the range of player {player}&apos;s shovel was detected, causing damage to enemy {enemyName}! ({damageAmount}).
        /// </summary>
        internal static string msg_Shovel5 {
            get {
                return ResourceManager.GetString("msg_Shovel5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player {player} was detected causing damage to enemy {enemyName} with his bare hands! ({damageAmount}).
        /// </summary>
        internal static string msg_Shovel6 {
            get {
                return ResourceManager.GetString("msg_Shovel6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;color=yellow&gt;[{player}] &lt;color=green&gt;New biological data is sent to the terminal! &lt;/color&gt;&lt;/color&gt;.
        /// </summary>
        internal static string msg_snc_player {
            get {
                return ResourceManager.GetString("msg_snc_player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detect player {player} to force provoking machine gun! (distance: {Distance}).
        /// </summary>
        internal static string msg_Turret {
            get {
                return ResourceManager.GetString("msg_Turret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detect player {player} to force provoking machine gun (empty hand)!.
        /// </summary>
        internal static string msg_Turret2 {
            get {
                return ResourceManager.GetString("msg_Turret2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;color=green&gt;Welcome &lt;color=yellow&gt;{player}&lt;/color&gt; to join the spaceship&lt;/color&gt;.
        /// </summary>
        internal static string msg_wlc_player {
            get {
                return ResourceManager.GetString("msg_wlc_player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Anti-cheating].
        /// </summary>
        internal static string Prefix {
            get {
                return ResourceManager.GetString("Prefix", resourceCulture);
            }
        }
    }
}
