//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AntiCheat.Lang {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class en_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal en_US() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AntiCheat.Lang.en_US", typeof(en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Provoking Boss Detection 的本地化字符串。
        /// </summary>
        internal static string config_Boss {
            get {
                return ResourceManager.GetString("config_Boss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fake chat message detection 的本地化字符串。
        /// </summary>
        internal static string config_ChatReal {
            get {
                return ResourceManager.GetString("config_ChatReal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Destory items detection 的本地化字符串。
        /// </summary>
        internal static string config_DespawnItem {
            get {
                return ResourceManager.GetString("config_DespawnItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Abnormal monster behavior detection 的本地化字符串。
        /// </summary>
        internal static string config_Enemy {
            get {
                return ResourceManager.GetString("config_Enemy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Free purchases 的本地化字符串。
        /// </summary>
        internal static string config_FreeBuy {
            get {
                return ResourceManager.GetString("config_FreeBuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Abnormal gift box interact detection 的本地化字符串。
        /// </summary>
        internal static string config_Gift {
            get {
                return ResourceManager.GetString("config_Gift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Item pickup distance detection 的本地化字符串。
        /// </summary>
        internal static string config_GrabObject {
            get {
                return ResourceManager.GetString("config_GrabObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Infinite ammo detection 的本地化字符串。
        /// </summary>
        internal static string config_InfiniteAmmo {
            get {
                return ResourceManager.GetString("config_InfiniteAmmo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invisible player detection 的本地化字符串。
        /// </summary>
        internal static string config_Invisibility {
            get {
                return ResourceManager.GetString("config_Invisibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Abnormal item interact cooldown detection 的本地化字符串。
        /// </summary>
        internal static string config_ItemCooldown {
            get {
                return ResourceManager.GetString("config_ItemCooldown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Jetpack explode detection 的本地化字符串。
        /// </summary>
        internal static string config_Jetpack {
            get {
                return ResourceManager.GetString("config_Jetpack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Kick player when this behavior is detected 的本地化字符串。
        /// </summary>
        internal static string config_Kick {
            get {
                return ResourceManager.GetString("config_Kick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Abnormal Enemy killed detection 的本地化字符串。
        /// </summary>
        internal static string config_KillEnemy {
            get {
                return ResourceManager.GetString("config_KillEnemy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Landmine detonate detection 的本地化字符串。
        /// </summary>
        internal static string config_Landmine {
            get {
                return ResourceManager.GetString("config_Landmine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 show log 的本地化字符串。
        /// </summary>
        internal static string config_Log {
            get {
                return ResourceManager.GetString("config_Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mini-map mod detection 的本地化字符串。
        /// </summary>
        internal static string config_Map {
            get {
                return ResourceManager.GetString("config_Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Abnormal masked enemy detection 的本地化字符串。
        /// </summary>
        internal static string config_Mask {
            get {
                return ResourceManager.GetString("config_Mask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Player name detection (Nameless or Unknown) 的本地化字符串。
        /// </summary>
        internal static string config_Nameless {
            get {
                return ResourceManager.GetString("config_Nameless", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set the lobby name prefix, Empty to disable. 的本地化字符串。
        /// </summary>
        internal static string config_Prefix {
            get {
                return ResourceManager.GetString("config_Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Abnormal furniture position detection 的本地化字符串。
        /// </summary>
        internal static string config_ShipBuild {
            get {
                return ResourceManager.GetString("config_ShipBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Client-side player can pull the lever only if more than the specified player number are reached (host permissions need to be turned off) 的本地化字符串。
        /// </summary>
        internal static string config_ShipConfig2 {
            get {
                return ResourceManager.GetString("config_ShipConfig2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Allow client-side player to take off when after this time (based on game world) 的本地化字符串。
        /// </summary>
        internal static string config_ShipConfig3 {
            get {
                return ResourceManager.GetString("config_ShipConfig3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Allow client-side player to take off when the number of alive players in the ship are exceed the specified ratio of total alive players number (0-100%) 的本地化字符串。
        /// </summary>
        internal static string config_ShipConfig4 {
            get {
                return ResourceManager.GetString("config_ShipConfig4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Detect malicious lever pull behavior (kick player when this behavior is detected) 的本地化字符串。
        /// </summary>
        internal static string config_ShipConfig5 {
            get {
                return ResourceManager.GetString("config_ShipConfig5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You are the host, your vote can call the autopilot. 的本地化字符串。
        /// </summary>
        internal static string config_ShipConfig6 {
            get {
                return ResourceManager.GetString("config_ShipConfig6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Light switch detection 的本地化字符串。
        /// </summary>
        internal static string config_ShipLight {
            get {
                return ResourceManager.GetString("config_ShipLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Only the host can land the ship 的本地化字符串。
        /// </summary>
        internal static string config_ShipSetting {
            get {
                return ResourceManager.GetString("config_ShipSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Terminal noise spaming detection 的本地化字符串。
        /// </summary>
        internal static string config_ShipTerminal {
            get {
                return ResourceManager.GetString("config_ShipTerminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Abnormal shovel damage detection 的本地化字符串。
        /// </summary>
        internal static string config_Shovel {
            get {
                return ResourceManager.GetString("config_Shovel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Spawn spiderweb detection 的本地化字符串。
        /// </summary>
        internal static string config_SpawnWebTrap {
            get {
                return ResourceManager.GetString("config_SpawnWebTrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Malicious attacking turret detection 的本地化字符串。
        /// </summary>
        internal static string config_Turret {
            get {
                return ResourceManager.GetString("config_Turret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 shotgun 的本地化字符串。
        /// </summary>
        internal static string Item_Shotgun {
            get {
                return ResourceManager.GetString("Item_Shotgun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 shovel 的本地化字符串。
        /// </summary>
        internal static string Item_Shovel {
            get {
                return ResourceManager.GetString("Item_Shovel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AntiCheat mod are Loaded! 的本地化字符串。
        /// </summary>
        internal static string log_load {
            get {
                return ResourceManager.GetString("log_load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {steamId}&apos;s attempt to reconnect to the game but was rejected (alreay kicked before)! 的本地化字符串。
        /// </summary>
        internal static string log_refuse_connect {
            get {
                return ResourceManager.GetString("log_refuse_connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;color=red&gt;{Prefix} {msg}&lt;/color&gt; 的本地化字符串。
        /// </summary>
        internal static string MessageFormat {
            get {
                return ResourceManager.GetString("MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;color=yellow&gt;[{player}] &lt;color=red&gt;was left behind.&lt;/color&gt;&lt;/color&gt; 的本地化字符串。
        /// </summary>
        internal static string msg_behind_player {
            get {
                return ResourceManager.GetString("msg_behind_player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Detected player {player} attempt to provoking the Boss! 的本地化字符串。
        /// </summary>
        internal static string msg_Boss {
            get {
                return ResourceManager.GetString("msg_Boss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Detected player {player} try to fake as {player2} in chat! 的本地化字符串。
        /// </summary>
        internal static string msg_ChatReal {
            get {
                return ResourceManager.GetString("msg_ChatReal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Detected player {player} destroying items! 的本地化字符串。
        /// </summary>
        internal static string msg_DespawnItem {
            get {
                return ResourceManager.GetString("msg_DespawnItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Detected player {player} try to change monster behavior! 的本地化字符串。
        /// </summary>
        internal static string msg_Enemy_ChangeOwnershipOfEnemy {
            get {
                return ResourceManager.GetString("msg_Enemy_ChangeOwnershipOfEnemy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Detected player {player} try to change monster behavior state! 的本地化字符串。
        /// </summary>
        internal static string msg_Enemy_SwitchToBehaviour {
            get {
                return ResourceManager.GetString("msg_Enemy_SwitchToBehaviour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Detected player {player} buying items for free! 的本地化字符串。
        /// </summary>
        internal static string msg_FreeBuy_Item {
            get {
                return ResourceManager.GetString("msg_FreeBuy_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Detected player {player} are modify credits({Money})! 的本地化字符串。
        /// </summary>
        internal static string msg_FreeBuy_SetMoney {
            get {
                return ResourceManager.GetString("msg_FreeBuy_SetMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Detected player {player} buying unlockable for free! 的本地化字符串。
        /// </summary>
        internal static string msg_FreeBuy_unlockable {
            get {
                return ResourceManager.GetString("msg_FreeBuy_unlockable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;color=green&gt;Anti-cheating (v{ver}) is enabled in this lobby&lt;/color&gt; 的本地化字符串。
        /// </summary>
        internal static string msg_game_start {
            get {
                return ResourceManager.GetString("msg_game_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Detected player {player} interact gift box abnormally! 的本地化字符串。
        /// </summary>
        internal static string msg_Gift {
            get {
                return ResourceManager.GetString("msg_Gift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Detected player {player} taking objects from too far away! (Player coordinates: {player_position}|Item coordinates: {object_position}) 的本地化字符串。
        /// </summary>
        internal static string msg_GrabObject {
            get {
                return ResourceManager.GetString("msg_GrabObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Detected player {player} have infinite ammo! 的本地化字符串。
        /// </summary>
        internal static string msg_InfiniteAmmo {
            get {
                return ResourceManager.GetString("msg_InfiniteAmmo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Detected player {player} are invisible! (Player coordinates: {player_position}) 的本地化字符串。
        /// </summary>
        internal static string msg_Invisibility {
            get {
                return ResourceManager.GetString("msg_Invisibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Detected player {player} using {item} without respect the cooldown! 的本地化字符串。
        /// </summary>
        internal static string msg_ItemCooldown {
            get {
                return ResourceManager.GetString("msg_ItemCooldown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Detected player {player} explode the jetpack! 的本地化字符串。
        /// </summary>
        internal static string msg_Jetpack {
            get {
                return ResourceManager.GetString("msg_Jetpack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {player} are now kicked! 的本地化字符串。
        /// </summary>
        internal static string msg_Kick {
            get {
                return ResourceManager.GetString("msg_Kick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Detected player {player} killing monster abnormally! ({enemyName}, remain HP before: {HP}) 的本地化字符串。
        /// </summary>
        internal static string msg_KillEnemy {
            get {
                return ResourceManager.GetString("msg_KillEnemy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Detected player {player} detonate the landmine abnormally! 的本地化字符串。
        /// </summary>
        internal static string msg_Landmine {
            get {
                return ResourceManager.GetString("msg_Landmine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Detected player {player} using minimap mod, that can make find the loot more easier! 的本地化字符串。
        /// </summary>
        internal static string msg_Map {
            get {
                return ResourceManager.GetString("msg_Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Detected player {player} spawn masked enemy abnormally, which mean that player catched by a masker but that player should already dead right now! 的本地化字符串。
        /// </summary>
        internal static string msg_Mask {
            get {
                return ResourceManager.GetString("msg_Mask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Detected player name abnormally, try to re-join? but if name are all numbers, your name will always be Nameless. 的本地化字符串。
        /// </summary>
        internal static string msg_Nameless {
            get {
                return ResourceManager.GetString("msg_Nameless", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Detected player {player} Remote Terminal! 的本地化字符串。
        /// </summary>
        internal static string msg_RemoteTerminal {
            get {
                return ResourceManager.GetString("msg_RemoteTerminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Detected player {player} placing furniture in abnormal position ({position})! 的本地化字符串。
        /// </summary>
        internal static string msg_ShipBuild {
            get {
                return ResourceManager.GetString("msg_ShipBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {player} Please wait until the number of people in the ship are reached {cfg} or more before pulling the lever, thx! 的本地化字符串。
        /// </summary>
        internal static string msg_ShipConfig2 {
            get {
                return ResourceManager.GetString("msg_ShipConfig2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {player} Please wait until the number of people in the ship are reached {player_count}({cfg4}%) and the time are reached {cfg3} to depart. (current time: {game_time}) 的本地化字符串。
        /// </summary>
        internal static string msg_ShipConfig4 {
            get {
                return ResourceManager.GetString("msg_ShipConfig4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Detected player {player} malicious use the ship lever! 的本地化字符串。
        /// </summary>
        internal static string msg_ShipConfig5 {
            get {
                return ResourceManager.GetString("msg_ShipConfig5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Detected player {player} switching light are too often! 的本地化字符串。
        /// </summary>
        internal static string msg_ShipLight {
            get {
                return ResourceManager.GetString("msg_ShipLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Detected player {player} making too many terminal noise! 的本地化字符串。
        /// </summary>
        internal static string msg_ShipTerminal {
            get {
                return ResourceManager.GetString("msg_ShipTerminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Detected player {player} using a shovel and cause abnormal damage to player {player2}! ({damageAmount}) 的本地化字符串。
        /// </summary>
        internal static string msg_Shovel {
            get {
                return ResourceManager.GetString("msg_Shovel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Detected player {player} abnormal shovel range, and damage to player {player2}! ({damageAmount}) 的本地化字符串。
        /// </summary>
        internal static string msg_Shovel2 {
            get {
                return ResourceManager.GetString("msg_Shovel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Detected player {player} damage to player {player2} without any weapon! ({damageAmount}) 的本地化字符串。
        /// </summary>
        internal static string msg_Shovel3 {
            get {
                return ResourceManager.GetString("msg_Shovel3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Detected player {player} using a shovel and cause abnormal damage to target {enemyName}! ({damageAmount}) 的本地化字符串。
        /// </summary>
        internal static string msg_Shovel4 {
            get {
                return ResourceManager.GetString("msg_Shovel4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Detected player {player} abnormal shovel range, and damage to target {enemyName}! ({damageAmount}) 的本地化字符串。
        /// </summary>
        internal static string msg_Shovel5 {
            get {
                return ResourceManager.GetString("msg_Shovel5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Detected player {player} damage to target {enemyName} without any weapon! ({damageAmount}) 的本地化字符串。
        /// </summary>
        internal static string msg_Shovel6 {
            get {
                return ResourceManager.GetString("msg_Shovel6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;color=yellow&gt;[{player}] &lt;color=green&gt;New biological data are sent to the terminal! &lt;/color&gt;&lt;/color&gt; 的本地化字符串。
        /// </summary>
        internal static string msg_snc_player {
            get {
                return ResourceManager.GetString("msg_snc_player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Detect player {player} malicious attacking the turret! (distance: {Distance}) 的本地化字符串。
        /// </summary>
        internal static string msg_Turret {
            get {
                return ResourceManager.GetString("msg_Turret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Detect player {player} malicious attacking the turret! (NO WEAPON)! 的本地化字符串。
        /// </summary>
        internal static string msg_Turret2 {
            get {
                return ResourceManager.GetString("msg_Turret2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You are the host, your vote can call the autopilot. 的本地化字符串。
        /// </summary>
        internal static string msg_vote {
            get {
                return ResourceManager.GetString("msg_vote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;color=green&gt;&lt;color=yellow&gt;[{player}]&lt;/color&gt; joined the ship.&lt;/color&gt; 的本地化字符串。
        /// </summary>
        internal static string msg_wlc_player {
            get {
                return ResourceManager.GetString("msg_wlc_player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [AntiCheat] 的本地化字符串。
        /// </summary>
        internal static string Prefix {
            get {
                return ResourceManager.GetString("Prefix", resourceCulture);
            }
        }
    }
}
