//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AntiCheat.Lang {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ko {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ko() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AntiCheat.Lang.ko", typeof(ko).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 플레이어가 회사 몬스터를 강제로 공격하게 하려고 시도할 때 이를 감지합니다. 的本地化字符串。
        /// </summary>
        internal static string config_Boss {
            get {
                return ResourceManager.GetString("config_Boss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 플레이어가 다른 플레이어의 이름으로 속이려고 할 때 이를 감지합니다. 的本地化字符串。
        /// </summary>
        internal static string config_ChatReal {
            get {
                return ResourceManager.GetString("config_ChatReal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 채팅 속도 제한 (밀리초) 的本地化字符串。
        /// </summary>
        internal static string config_ChatReal_Cooldown {
            get {
                return ResourceManager.GetString("config_ChatReal_Cooldown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 아이템이 비정상적으로 파괴되거나 삭제될 때 이를 감지합니다. 的本地化字符串。
        /// </summary>
        internal static string config_DespawnItem {
            get {
                return ResourceManager.GetString("config_DespawnItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 메시지 표시 유형을 감지합니다. PublicChat = 방 공개 채팅에 표시, HostChat = 호스트만 채팅에 표시, GUI = GUI 인터페이스에 표시 的本地化字符串。
        /// </summary>
        internal static string config_DetectedMessageType {
            get {
                return ResourceManager.GetString("config_DetectedMessageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 몬스터가 비정상적으로 행동할 때 이를 감지합니다. 的本地化字符串。
        /// </summary>
        internal static string config_Enemy {
            get {
                return ResourceManager.GetString("config_Enemy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 플레이어가 무료로 아이템을 주문하는것을 감지합니다. 的本地化字符串。
        /// </summary>
        internal static string config_FreeBuy {
            get {
                return ResourceManager.GetString("config_FreeBuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 플레이어가 비정상적인 선물 상자 상호작용을 감지합니다. 的本地化字符串。
        /// </summary>
        internal static string config_Gift {
            get {
                return ResourceManager.GetString("config_Gift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 기본 잡기 범위 밖에서 아이템을 집을 때 이를 감지합니다. 的本地化字符串。
        /// </summary>
        internal static string config_GrabObject {
            get {
                return ResourceManager.GetString("config_GrabObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 플레이어가 벨트 가방으로 스크랩을 집는 것을 비활성화합니다. (가방모드 비활성화) 的本地化字符串。
        /// </summary>
        internal static string config_GrabObject_BeltBag {
            get {
                return ResourceManager.GetString("config_GrabObject_BeltBag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 플레이어가 4개 이상의 아이템을 집는 것을 방지합니다. 的本地化字符串。
        /// </summary>
        internal static string config_GrabObject_MoreSlot {
            get {
                return ResourceManager.GetString("config_GrabObject_MoreSlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 플레이어가 동시에 여러 개의 양손 아이템을 집는 것을 방지합니다. (양손모드 비활성화) 的本地化字符串。
        /// </summary>
        internal static string config_GrabObject_TwoHand {
            get {
                return ResourceManager.GetString("config_GrabObject_TwoHand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 플레이어가 음수 피해를 사용하여 체력을 회복할 때 이를 감지합니다. (healthstation같은거 비활성화) 的本地化字符串。
        /// </summary>
        internal static string config_Health_Recover {
            get {
                return ResourceManager.GetString("config_Health_Recover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ignore client configuration differences (this will mitigate the case of client errors) 的本地化字符串。
        /// </summary>
        internal static string config_IgnoreClientConfig {
            get {
                return ResourceManager.GetString("config_IgnoreClientConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 플레이어가 무한 탄약을 사용할 때 이를 감지합니다. 참고: 이미 무한 탄약이 주어진 샷건을 사용하는 정상적인 플레이어도 무한 탄약을 사용하는 것으로 감지될 수 있습니다. 的本地化字符串。
        /// </summary>
        internal static string config_InfiniteAmmo {
            get {
                return ResourceManager.GetString("config_InfiniteAmmo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 보이지 않는 플레이어를 감지합니다. 的本地化字符串。
        /// </summary>
        internal static string config_Invisibility {
            get {
                return ResourceManager.GetString("config_Invisibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 플레이어가 아이템을 너무 빨리 사용할 때 이를 감지합니다. 的本地化字符串。
        /// </summary>
        internal static string config_ItemCooldown {
            get {
                return ResourceManager.GetString("config_ItemCooldown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 플레이어가 제트팩 폭발을 강제할 때 이를 감지합니다. 的本地化字符串。
        /// </summary>
        internal static string config_Jetpack {
            get {
                return ResourceManager.GetString("config_Jetpack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 이 행동이 감지되면 플레이어를 킥합니다. 的本地化字符串。
        /// </summary>
        internal static string config_Kick {
            get {
                return ResourceManager.GetString("config_Kick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 적이 즉시 죽을 때 이를 감지합니다. 삽의 공격력을 100이 아닙니다!!! 的本地化字符串。
        /// </summary>
        internal static string config_KillEnemy {
            get {
                return ResourceManager.GetString("config_KillEnemy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 플레이어가 비정상적으로 지뢰를 폭발시킬 때 이를 감지합니다. 的本地化字符串。
        /// </summary>
        internal static string config_Landmine {
            get {
                return ResourceManager.GetString("config_Landmine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 로그를 표시합니다. 的本地化字符串。
        /// </summary>
        internal static string config_Log {
            get {
                return ResourceManager.GetString("config_Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 미니맵 모드를 사용할 때 이를 감지합니다. 的本地化字符串。
        /// </summary>
        internal static string config_Map {
            get {
                return ResourceManager.GetString("config_Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 가면을 쓴 적이 비정상적으로 생성될 때 이를 감지합니다. 的本地化字符串。
        /// </summary>
        internal static string config_Mask {
            get {
                return ResourceManager.GetString("config_Mask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 이름이 없거나 알 수 없는 플레이어 이름을 감지합니다. 的本地化字符串。
        /// </summary>
        internal static string config_Nameless {
            get {
                return ResourceManager.GetString("config_Nameless", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Client-side player action logs 的本地化字符串。
        /// </summary>
        internal static string config_OperationLog {
            get {
                return ResourceManager.GetString("config_OperationLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 플레이어의 비정상적인 운반 무게를 감지합니다. 的本地化字符串。
        /// </summary>
        internal static string config_PlayerCarryWeight {
            get {
                return ResourceManager.GetString("config_PlayerCarryWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 플레이어의 운반 무게를 복원합니다. 的本地化字符串。
        /// </summary>
        internal static string config_PlayerCarryWeight2 {
            get {
                return ResourceManager.GetString("config_PlayerCarryWeight2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 로비 이름 앞에 괄호로 텍스트를 넣습니다. 비활성화하려면 비워 두세여. 的本地化字符串。
        /// </summary>
        internal static string config_Prefix {
            get {
                return ResourceManager.GetString("config_Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 플레이어가 원격으로 터미널을 사용할 때 이를 감지합니다. 的本地化字符串。
        /// </summary>
        internal static string config_RemoteTerminal {
            get {
                return ResourceManager.GetString("config_RemoteTerminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RPC 보고 감지 지연, 플레이어가 이 시간 후에 RPC를 보고하는지 감지합니다 (밀리초 단위) 的本地化字符串。
        /// </summary>
        internal static string config_RPCReport_Delay {
            get {
                return ResourceManager.GetString("config_RPCReport_Delay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 히트 RPC 보고 감지, 플레이어가 공격을 받고 피를 흘리지 않는 경우 감지됩니다 (무적 감지) 的本地化字符串。
        /// </summary>
        internal static string config_RPCReport_Hit {
            get {
                return ResourceManager.GetString("config_RPCReport_Hit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 KillPlayer RPC 보고 감지, 플레이어가 죽었지만 죽음을 보고하지 않는 경우 감지됩니다 (무적 감지) 的本地化字符串。
        /// </summary>
        internal static string config_RPCReport_KillPlayer {
            get {
                return ResourceManager.GetString("config_RPCReport_KillPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 비정상적으로 배치되는걸 감지합니다. 的本地化字符串。
        /// </summary>
        internal static string config_ShipBuild {
            get {
                return ResourceManager.GetString("config_ShipBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 이 플레이어 수에 도달하면 클라이언트가 레버를 당길 수 있습니다. (StartGameOnlyHost가 false로 설정되어야 합니다.) 的本地化字符串。
        /// </summary>
        internal static string config_ShipConfig2 {
            get {
                return ResourceManager.GetString("config_ShipConfig2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 이 게임 시간이 지나면 클라이언트가 이륙할 수 있습니다. 的本地化字符串。
        /// </summary>
        internal static string config_ShipConfig3 {
            get {
                return ResourceManager.GetString("config_ShipConfig3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 함선에 있는 생존 플레이어 수가 지정된 비율 이상일 때 클라이언트가 이륙할 수 있습니다. (0-100%) 的本地化字符串。
        /// </summary>
        internal static string config_ShipConfig4 {
            get {
                return ResourceManager.GetString("config_ShipConfig4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 플레이어가 함선 레버를 강제로 작동시키려고 할 때 이를 감지합니다. 감지되면 플레이어를 킥합니다. 的本地化字符串。
        /// </summary>
        internal static string config_ShipConfig5 {
            get {
                return ResourceManager.GetString("config_ShipConfig5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 호스트로서 단일 투표로 자동 조종을 즉시 강제할 수 있습니다. 的本地化字符串。
        /// </summary>
        internal static string config_ShipConfig6 {
            get {
                return ResourceManager.GetString("config_ShipConfig6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 플레이어가 너무 빨리 조명을 전환할 때 이를 감지합니다. 的本地化字符串。
        /// </summary>
        internal static string config_ShipLight {
            get {
                return ResourceManager.GetString("config_ShipLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 호스트만이 함선을 착륙시킬 수 있습니다. 的本地化字符串。
        /// </summary>
        internal static string config_ShipSetting {
            get {
                return ResourceManager.GetString("config_ShipSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 터미널 소음사용하여 시끄럽게 할 때 이를 감지합니다. 的本地化字符串。
        /// </summary>
        internal static string config_ShipTerminal {
            get {
                return ResourceManager.GetString("config_ShipTerminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 비정상적인 삽 피해를 감지합니다. 的本地化字符串。
        /// </summary>
        internal static string config_Shovel {
            get {
                return ResourceManager.GetString("config_Shovel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 플레이어가 무기 없이 피해를 입힐 수 있도록 허용합니다. 네트워크 비동기화로 인해 다른 플레이어의 활성 인벤토리 슬롯이 비동기화될 수 있습니다. 的本地化字符串。
        /// </summary>
        internal static string config_Shovel2 {
            get {
                return ResourceManager.GetString("config_Shovel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 플레이어가 거미줄을 생성하려고 할 때 이를 감지합니다. 的本地化字符串。
        /// </summary>
        internal static string config_SpawnWebTrap {
            get {
                return ResourceManager.GetString("config_SpawnWebTrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 플레이어가 터렛을 폭주시키려고 할 때 이를 감지합니다. 的本地化字符串。
        /// </summary>
        internal static string config_Turret {
            get {
                return ResourceManager.GetString("config_Turret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Kitchen knife 的本地化字符串。
        /// </summary>
        internal static string Item_Knife {
            get {
                return ResourceManager.GetString("Item_Knife", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 shotgun 的本地化字符串。
        /// </summary>
        internal static string Item_Shotgun {
            get {
                return ResourceManager.GetString("Item_Shotgun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 shovel 的本地化字符串。
        /// </summary>
        internal static string Item_Shovel {
            get {
                return ResourceManager.GetString("Item_Shovel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AntiCheat 모드 로드 성공! 的本地化字符串。
        /// </summary>
        internal static string log_load {
            get {
                return ResourceManager.GetString("log_load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {steamId}가 게임에 접속을 시도했으나 거부되었습니다! (이미 킥됨) 的本地化字符串。
        /// </summary>
        internal static string log_refuse_connect {
            get {
                return ResourceManager.GetString("log_refuse_connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;color=red&gt;{Prefix} {msg}&lt;/color&gt; 的本地化字符串。
        /// </summary>
        internal static string MessageFormat {
            get {
                return ResourceManager.GetString("MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;color=yellow&gt;[{player}] &lt;color=red&gt;was left behind.&lt;/color&gt;&lt;/color&gt; 的本地化字符串。
        /// </summary>
        internal static string msg_behind_player {
            get {
                return ResourceManager.GetString("msg_behind_player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {player}가 회사 몬스터를 강제로 공격하게 하려고 시도하는 것이 감지되었습니다! 的本地化字符串。
        /// </summary>
        internal static string msg_Boss {
            get {
                return ResourceManager.GetString("msg_Boss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {player}가 유료 달을 무료 달로 변경하려고 시도하는 것이 감지되었습니다! (이 행동은 호스트에게만 허용됩니다!) 的本地化字符串。
        /// </summary>
        internal static string msg_ChangeLevel {
            get {
                return ResourceManager.GetString("msg_ChangeLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {player}가 {player2}의 이름으로 채팅을 속이려고 시도했습니다! 的本地化字符串。
        /// </summary>
        internal static string msg_ChatReal {
            get {
                return ResourceManager.GetString("msg_ChatReal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {player}가 아이템을 파괴하는 것이 감지되었습니다! 的本地化字符串。
        /// </summary>
        internal static string msg_DespawnItem {
            get {
                return ResourceManager.GetString("msg_DespawnItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {player}가 몬스터의 행동을 변경하려고 시도하는 것이 감지되었습니다! 的本地化字符串。
        /// </summary>
        internal static string msg_Enemy_ChangeOwnershipOfEnemy {
            get {
                return ResourceManager.GetString("msg_Enemy_ChangeOwnershipOfEnemy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {player}가 몬스터의 상태를 변경하려고 시도하는 것이 감지되었습니다! 的本地化字符串。
        /// </summary>
        internal static string msg_Enemy_SwitchToBehaviour {
            get {
                return ResourceManager.GetString("msg_Enemy_SwitchToBehaviour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {player}가 무료로 아이템을 구매하는 것이 감지되었습니다! 的本地化字符串。
        /// </summary>
        internal static string msg_FreeBuy_Item {
            get {
                return ResourceManager.GetString("msg_FreeBuy_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {player}가 유료 달로 무료로 이동하려고 시도하는 것이 감지되었습니다! 的本地化字符串。
        /// </summary>
        internal static string msg_FreeBuy_Level {
            get {
                return ResourceManager.GetString("msg_FreeBuy_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {player}가 함선의 크레딧을 수정하는 것이 감지되었습니다! ({Money})! 的本地化字符串。
        /// </summary>
        internal static string msg_FreeBuy_SetMoney {
            get {
                return ResourceManager.GetString("msg_FreeBuy_SetMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {player}가 함선 잠금 해제를 무료로 구매하는 것이 감지되었습니다! 的本地化字符串。
        /// </summary>
        internal static string msg_FreeBuy_unlockable {
            get {
                return ResourceManager.GetString("msg_FreeBuy_unlockable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;color=green&gt;이 로비에서 Anti-Cheat (v{ver})가 활성화되었습니다&lt;/color&gt; 的本地化字符串。
        /// </summary>
        internal static string msg_game_start {
            get {
                return ResourceManager.GetString("msg_game_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {player}가 선물 상자를 비정상적으로 작동시키는 것이 감지되었습니다! 的本地化字符串。
        /// </summary>
        internal static string msg_Gift {
            get {
                return ResourceManager.GetString("msg_Gift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {player}가 너무 멀리서 아이템을 집는 것이 감지되었습니다! (플레이어 좌표: {player_position}|아이템 좌표: {object_position}) 的本地化字符串。
        /// </summary>
        internal static string msg_GrabObject {
            get {
                return ResourceManager.GetString("msg_GrabObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {player}가 체력을 회복하는 것이 감지되었습니다 ({hp})! 的本地化字符串。
        /// </summary>
        internal static string msg_Health_Recover {
            get {
                return ResourceManager.GetString("msg_Health_Recover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {player}가 무한 탄약을 사용하는 것이 감지되었습니다! 的本地化字符串。
        /// </summary>
        internal static string msg_InfiniteAmmo {
            get {
                return ResourceManager.GetString("msg_InfiniteAmmo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {player}가 보이지 않는 상태인 것이 감지되었습니다! (플레이어 좌표: {player_position}) 的本地化字符串。
        /// </summary>
        internal static string msg_Invisibility {
            get {
                return ResourceManager.GetString("msg_Invisibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {player}가 아이템을 너무 빨리 사용하는 것이 감지되었습니다! 的本地化字符串。
        /// </summary>
        internal static string msg_ItemCooldown {
            get {
                return ResourceManager.GetString("msg_ItemCooldown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {player}가 제트팩 폭발을 강제하는 것이 감지되었습니다! 的本地化字符串。
        /// </summary>
        internal static string msg_Jetpack {
            get {
                return ResourceManager.GetString("msg_Jetpack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {player}가 킥되었습니다! 的本地化字符串。
        /// </summary>
        internal static string msg_Kick {
            get {
                return ResourceManager.GetString("msg_Kick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 치트가 감지되었습니다 的本地化字符串。
        /// </summary>
        internal static string msg_KickPlayer {
            get {
                return ResourceManager.GetString("msg_KickPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {player}가 몬스터를 즉시 죽이는 것이 감지되었습니다! ({enemyName}, 몬스터 HP 이전: {HP}) 的本地化字符串。
        /// </summary>
        internal static string msg_KillEnemy {
            get {
                return ResourceManager.GetString("msg_KillEnemy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {player}가 지뢰를 강제로 폭발시키는 것이 감지되었습니다! 的本地化字符串。
        /// </summary>
        internal static string msg_Landmine {
            get {
                return ResourceManager.GetString("msg_Landmine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {player}가 미니맵 모드를 사용하는 것이 감지되었습니다! 的本地化字符串。
        /// </summary>
        internal static string msg_Map {
            get {
                return ResourceManager.GetString("msg_Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {player}가 가면을 쓴 적을 비정상적으로 생성하는 것이 감지되었습니다! 的本地化字符串。
        /// </summary>
        internal static string msg_Mask {
            get {
                return ResourceManager.GetString("msg_Mask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {player}가 이름이 없거나 알 수 없는 이름을 사용하는 것이 감지되었습니다! 的本地化字符串。
        /// </summary>
        internal static string msg_Nameless {
            get {
                return ResourceManager.GetString("msg_Nameless", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {player}가 비정상적인 운반 무게를 사용하는 것이 감지되었습니다! 的本地化字符串。
        /// </summary>
        internal static string msg_PlayerCarryWeight {
            get {
                return ResourceManager.GetString("msg_PlayerCarryWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 운반 무게가 강제로 복원되었습니다! 的本地化字符串。
        /// </summary>
        internal static string msg_PlayerCarryWeight_Recovery {
            get {
                return ResourceManager.GetString("msg_PlayerCarryWeight_Recovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {player}가 원격으로 터미널을 사용하는 것이 감지되었습니다! 的本地化字符串。
        /// </summary>
        internal static string msg_RemoteTerminal {
            get {
                return ResourceManager.GetString("msg_RemoteTerminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {player}가 {RPC} RPC를 보고하지 않는 것이 감지되었습니다! 的本地化字符串。
        /// </summary>
        internal static string msg_RPCReport {
            get {
                return ResourceManager.GetString("msg_RPCReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {player}가 가구를 비정상적인 위치에 배치하는 것이 감지되었습니다! ({position}) 的本地化字符串。
        /// </summary>
        internal static string msg_ShipBuild {
            get {
                return ResourceManager.GetString("msg_ShipBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {player}, 레버를 당기기 전에 함선에 있는 사람 수가 {cfg} 이상이 될 때까지 기다려 주세요, 감사합니다! 的本地化字符串。
        /// </summary>
        internal static string msg_ShipConfig2 {
            get {
                return ResourceManager.GetString("msg_ShipConfig2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {player}, 함선에 있는 사람 수가 {player_count}({cfg4}%) 이상이고 시간이 {cfg3}에 도달할 때까지 기다려 주세요. (현재 시간: {game_time}) 的本地化字符串。
        /// </summary>
        internal static string msg_ShipConfig4 {
            get {
                return ResourceManager.GetString("msg_ShipConfig4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {player}가 함선 레버를 강제로 작동시키려고 시도하는 것이 감지되었습니다! 的本地化字符串。
        /// </summary>
        internal static string msg_ShipConfig5 {
            get {
                return ResourceManager.GetString("msg_ShipConfig5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {player}가 너무 빨리 조명을 전환하는 것이 감지되었습니다! 的本地化字符串。
        /// </summary>
        internal static string msg_ShipLight {
            get {
                return ResourceManager.GetString("msg_ShipLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {player}가 터미널 소음을 너무 많이 내는 것이 감지되었습니다! 的本地化字符串。
        /// </summary>
        internal static string msg_ShipTerminal {
            get {
                return ResourceManager.GetString("msg_ShipTerminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {player}가 {player2}에게 {item}으로 비정상적인 피해를 입히는 것이 감지되었습니다! ({damageAmount}) 的本地化字符串。
        /// </summary>
        internal static string msg_Shovel {
            get {
                return ResourceManager.GetString("msg_Shovel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {player}가 비정상적인 삽 범위로 {player2}에게 피해를 입히는 것이 감지되었습니다! ({damageAmount}) 的本地化字符串。
        /// </summary>
        internal static string msg_Shovel2 {
            get {
                return ResourceManager.GetString("msg_Shovel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {player}가 무기 없이 {player2}에게 피해를 입히는 것이 감지되었습니다! ({damageAmount}) 的本地化字符串。
        /// </summary>
        internal static string msg_Shovel3 {
            get {
                return ResourceManager.GetString("msg_Shovel3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {player}가 {enemyName}에게 {item}으로 비정상적인 피해를 입히는 것이 감지되었습니다! ({damageAmount}) 的本地化字符串。
        /// </summary>
        internal static string msg_Shovel4 {
            get {
                return ResourceManager.GetString("msg_Shovel4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {player}가 비정상적인 삽 범위로 {enemyName}에게 피해를 입히는 것이 감지되었습니다! ({damageAmount}) 的本地化字符串。
        /// </summary>
        internal static string msg_Shovel5 {
            get {
                return ResourceManager.GetString("msg_Shovel5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {player}가 무기 없이 {enemyName}에게 피해를 입히는 것이 감지되었습니다! ({damageAmount}) 的本地化字符串。
        /// </summary>
        internal static string msg_Shovel6 {
            get {
                return ResourceManager.GetString("msg_Shovel6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;color=yellow&gt;[{player}] &lt;color=green&gt;터미널에 새로운 생물 데이터를 보냈습니다! &lt;/color&gt;&lt;/color&gt; 的本地化字符串。
        /// </summary>
        internal static string msg_snc_player {
            get {
                return ResourceManager.GetString("msg_snc_player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {player}가 터렛을 폭주시키는 것이 감지되었습니다! (거리: {Distance}) 的本地化字符串。
        /// </summary>
        internal static string msg_Turret {
            get {
                return ResourceManager.GetString("msg_Turret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {player}가 무기 없이 터렛을 폭주시키는 것이 감지되었습니다! 的本地化字符串。
        /// </summary>
        internal static string msg_Turret2 {
            get {
                return ResourceManager.GetString("msg_Turret2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 당신은 호스트입니다, 당신의 투표는 자동 조종을 강제할 수 있습니다. 的本地化字符串。
        /// </summary>
        internal static string msg_vote {
            get {
                return ResourceManager.GetString("msg_vote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {player}가 함선의 조기 출발을 위해 투표했습니다. ({now}/{max}) 的本地化字符串。
        /// </summary>
        internal static string msg_vote_player {
            get {
                return ResourceManager.GetString("msg_vote_player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;color=green&gt;&lt;color=yellow&gt;[{player}]&lt;/color&gt;가 함선에 탑승했습니다.&lt;/color&gt; 的本地化字符串。
        /// </summary>
        internal static string msg_wlc_player {
            get {
                return ResourceManager.GetString("msg_wlc_player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ActionLog] {player} purchased {items} 的本地化字符串。
        /// </summary>
        internal static string OperationLog_BuyItem {
            get {
                return ResourceManager.GetString("OperationLog_BuyItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ActionLog] {player} purchased {unlockable} 的本地化字符串。
        /// </summary>
        internal static string OperationLog_BuyShipUnlockable {
            get {
                return ResourceManager.GetString("OperationLog_BuyShipUnlockable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ActionLog] {player} routed to moon {planet} 的本地化字符串。
        /// </summary>
        internal static string OperationLog_ChangeLevel_ {
            get {
                return ResourceManager.GetString("OperationLog_ChangeLevel ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {player} is joining... 的本地化字符串。
        /// </summary>
        internal static string OperationLog_JoinLobby {
            get {
                return ResourceManager.GetString("OperationLog_JoinLobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [AntiCheat] 的本地化字符串。
        /// </summary>
        internal static string Prefix {
            get {
                return ResourceManager.GetString("Prefix", resourceCulture);
            }
        }
    }
}
