//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AntiCheat.Lang {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class zh_CN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal zh_CN() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AntiCheat.Lang.zh_CN", typeof(zh_CN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 召唤老板检测 的本地化字符串。
        /// </summary>
        internal static string config_Boss {
            get {
                return ResourceManager.GetString("config_Boss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发言伪造检测 的本地化字符串。
        /// </summary>
        internal static string config_ChatReal {
            get {
                return ResourceManager.GetString("config_ChatReal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 销毁物品检测 的本地化字符串。
        /// </summary>
        internal static string config_DespawnItem {
            get {
                return ResourceManager.GetString("config_DespawnItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 怪物异常检测 的本地化字符串。
        /// </summary>
        internal static string config_Enemy {
            get {
                return ResourceManager.GetString("config_Enemy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 零元购检测 的本地化字符串。
        /// </summary>
        internal static string config_FreeBuy {
            get {
                return ResourceManager.GetString("config_FreeBuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 刷礼物盒检测 的本地化字符串。
        /// </summary>
        internal static string config_Gift {
            get {
                return ResourceManager.GetString("config_Gift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 隔空取物检测 的本地化字符串。
        /// </summary>
        internal static string config_GrabObject {
            get {
                return ResourceManager.GetString("config_GrabObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无限子弹检测 的本地化字符串。
        /// </summary>
        internal static string config_InfiniteAmmo {
            get {
                return ResourceManager.GetString("config_InfiniteAmmo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 隐身检测 的本地化字符串。
        /// </summary>
        internal static string config_Invisibility {
            get {
                return ResourceManager.GetString("config_Invisibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 物品使用冷却异常检测 的本地化字符串。
        /// </summary>
        internal static string config_ItemCooldown {
            get {
                return ResourceManager.GetString("config_ItemCooldown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 喷气背包爆炸检测 的本地化字符串。
        /// </summary>
        internal static string config_Jetpack {
            get {
                return ResourceManager.GetString("config_Jetpack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检测到该行为时踢出玩家 的本地化字符串。
        /// </summary>
        internal static string config_Kick {
            get {
                return ResourceManager.GetString("config_Kick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 秒杀敌人检测 的本地化字符串。
        /// </summary>
        internal static string config_KillEnemy {
            get {
                return ResourceManager.GetString("config_KillEnemy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 引爆地雷检测 的本地化字符串。
        /// </summary>
        internal static string config_Landmine {
            get {
                return ResourceManager.GetString("config_Landmine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示控制台日志 的本地化字符串。
        /// </summary>
        internal static string config_Log {
            get {
                return ResourceManager.GetString("config_Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 小地图检测 的本地化字符串。
        /// </summary>
        internal static string config_Map {
            get {
                return ResourceManager.GetString("config_Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 刷假人检测 的本地化字符串。
        /// </summary>
        internal static string config_Mask {
            get {
                return ResourceManager.GetString("config_Mask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 玩家名字检测(Nameless或Unknown) 的本地化字符串。
        /// </summary>
        internal static string config_Nameless {
            get {
                return ResourceManager.GetString("config_Nameless", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置房间名前缀，使用空值代表不启用前缀 的本地化字符串。
        /// </summary>
        internal static string config_Prefix {
            get {
                return ResourceManager.GetString("config_Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 远程终端检测 的本地化字符串。
        /// </summary>
        internal static string config_RemoteTerminal {
            get {
                return ResourceManager.GetString("config_RemoteTerminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 飞船物品位置异常检测 的本地化字符串。
        /// </summary>
        internal static string config_ShipBuild {
            get {
                return ResourceManager.GetString("config_ShipBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 非房主只有在超过指定人数才能进行着陆(需要关闭房主权限) 的本地化字符串。
        /// </summary>
        internal static string config_ShipConfig2 {
            get {
                return ResourceManager.GetString("config_ShipConfig2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 非房主只有在该时间点以后才能起飞 的本地化字符串。
        /// </summary>
        internal static string config_ShipConfig3 {
            get {
                return ResourceManager.GetString("config_ShipConfig3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 非房主只有在当飞船存活人数超过总存活人数时才能起飞(0-100%) 的本地化字符串。
        /// </summary>
        internal static string config_ShipConfig4 {
            get {
                return ResourceManager.GetString("config_ShipConfig4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检测强制拉杆行为(检测到该行为时踢出玩家) 的本地化字符串。
        /// </summary>
        internal static string config_ShipConfig5 {
            get {
                return ResourceManager.GetString("config_ShipConfig5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 作为房主，你可以一票起飞 的本地化字符串。
        /// </summary>
        internal static string config_ShipConfig6 {
            get {
                return ResourceManager.GetString("config_ShipConfig6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 灯关秀检测 的本地化字符串。
        /// </summary>
        internal static string config_ShipLight {
            get {
                return ResourceManager.GetString("config_ShipLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 只有房主才有着陆权限 的本地化字符串。
        /// </summary>
        internal static string config_ShipSetting {
            get {
                return ResourceManager.GetString("config_ShipSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 终端噪音检测 的本地化字符串。
        /// </summary>
        internal static string config_ShipTerminal {
            get {
                return ResourceManager.GetString("config_ShipTerminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 铲子伤害检测 的本地化字符串。
        /// </summary>
        internal static string config_Shovel {
            get {
                return ResourceManager.GetString("config_Shovel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 允许玩家空手时能造成正常伤害(网络延迟可能会导致玩家空手) 的本地化字符串。
        /// </summary>
        internal static string config_Shovel2 {
            get {
                return ResourceManager.GetString("config_Shovel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 刷蜘蛛网检测 的本地化字符串。
        /// </summary>
        internal static string config_SpawnWebTrap {
            get {
                return ResourceManager.GetString("config_SpawnWebTrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 激怒机枪检测 的本地化字符串。
        /// </summary>
        internal static string config_Turret {
            get {
                return ResourceManager.GetString("config_Turret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 小刀 的本地化字符串。
        /// </summary>
        internal static string Item_Knife {
            get {
                return ResourceManager.GetString("Item_Knife", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 霰弹枪 的本地化字符串。
        /// </summary>
        internal static string Item_Shotgun {
            get {
                return ResourceManager.GetString("Item_Shotgun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 铲子 的本地化字符串。
        /// </summary>
        internal static string Item_Shovel {
            get {
                return ResourceManager.GetString("Item_Shovel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 反作弊模组已加载完毕！ 的本地化字符串。
        /// </summary>
        internal static string log_load {
            get {
                return ResourceManager.GetString("log_load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {steamId} 尝试重连游戏被拒绝(已被踢出)！ 的本地化字符串。
        /// </summary>
        internal static string log_refuse_connect {
            get {
                return ResourceManager.GetString("log_refuse_connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;color=red&gt;{Prefix} {msg}&lt;/color&gt; 的本地化字符串。
        /// </summary>
        internal static string MessageFormat {
            get {
                return ResourceManager.GetString("MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;color=yellow&gt;[{player}] &lt;color=red&gt;被抛弃了&lt;/color&gt;&lt;/color&gt; 的本地化字符串。
        /// </summary>
        internal static string msg_behind_player {
            get {
                return ResourceManager.GetString("msg_behind_player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检测到玩家 {player} 召唤老板！ 的本地化字符串。
        /// </summary>
        internal static string msg_Boss {
            get {
                return ResourceManager.GetString("msg_Boss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检测到玩家 {player} 尝试伪装成 {player2} 发言！ 的本地化字符串。
        /// </summary>
        internal static string msg_ChatReal {
            get {
                return ResourceManager.GetString("msg_ChatReal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检测到玩家 {player} 销毁物品 ({item})！ 的本地化字符串。
        /// </summary>
        internal static string msg_DespawnItem {
            get {
                return ResourceManager.GetString("msg_DespawnItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检测到玩家 {player} 强制改变怪物仇恨！ 的本地化字符串。
        /// </summary>
        internal static string msg_Enemy_ChangeOwnershipOfEnemy {
            get {
                return ResourceManager.GetString("msg_Enemy_ChangeOwnershipOfEnemy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检测到玩家 {player} 强制改变怪物状态！ 的本地化字符串。
        /// </summary>
        internal static string msg_Enemy_SwitchToBehaviour {
            get {
                return ResourceManager.GetString("msg_Enemy_SwitchToBehaviour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检测到玩家 {player} 强制购买物品！ 的本地化字符串。
        /// </summary>
        internal static string msg_FreeBuy_Item {
            get {
                return ResourceManager.GetString("msg_FreeBuy_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检测到玩家 {player} 强制切换付费星球！ 的本地化字符串。
        /// </summary>
        internal static string msg_FreeBuy_Level {
            get {
                return ResourceManager.GetString("msg_FreeBuy_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检测到玩家 {player} 修改金钱({Money})！ 的本地化字符串。
        /// </summary>
        internal static string msg_FreeBuy_SetMoney {
            get {
                return ResourceManager.GetString("msg_FreeBuy_SetMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检测到玩家 {player} 强制解锁飞船装饰！ 的本地化字符串。
        /// </summary>
        internal static string msg_FreeBuy_unlockable {
            get {
                return ResourceManager.GetString("msg_FreeBuy_unlockable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;color=green&gt;本房间启用反作弊(v{ver})&lt;/color&gt; 的本地化字符串。
        /// </summary>
        internal static string msg_game_start {
            get {
                return ResourceManager.GetString("msg_game_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检测到玩家 {player} 刷礼物盒！ 的本地化字符串。
        /// </summary>
        internal static string msg_Gift {
            get {
                return ResourceManager.GetString("msg_Gift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检测到玩家 {player} 隔空取物！(玩家坐标：{player_position}|物品坐标：{object_position}) 的本地化字符串。
        /// </summary>
        internal static string msg_GrabObject {
            get {
                return ResourceManager.GetString("msg_GrabObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检测到玩家 {player} 正使用无限子弹！ 的本地化字符串。
        /// </summary>
        internal static string msg_InfiniteAmmo {
            get {
                return ResourceManager.GetString("msg_InfiniteAmmo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检测到玩家 {player} 坐标异常！(玩家坐标：{player_position}) 的本地化字符串。
        /// </summary>
        internal static string msg_Invisibility {
            get {
                return ResourceManager.GetString("msg_Invisibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检测到玩家 {player} 使用 {item} 频率异常！ 的本地化字符串。
        /// </summary>
        internal static string msg_ItemCooldown {
            get {
                return ResourceManager.GetString("msg_ItemCooldown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检测到玩家 {player} 引爆喷气背包！ 的本地化字符串。
        /// </summary>
        internal static string msg_Jetpack {
            get {
                return ResourceManager.GetString("msg_Jetpack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {player} 已被踢出 的本地化字符串。
        /// </summary>
        internal static string msg_Kick {
            get {
                return ResourceManager.GetString("msg_Kick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检测到玩家 {player} 秒杀怪物！( {enemyName} ,剩余血量:{HP}) 的本地化字符串。
        /// </summary>
        internal static string msg_KillEnemy {
            get {
                return ResourceManager.GetString("msg_KillEnemy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检测到玩家 {player} 强制引爆地雷！ 的本地化字符串。
        /// </summary>
        internal static string msg_Landmine {
            get {
                return ResourceManager.GetString("msg_Landmine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检测到玩家 {player} 使用小地图！ 的本地化字符串。
        /// </summary>
        internal static string msg_Map {
            get {
                return ResourceManager.GetString("msg_Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检测到玩家 {player} 刷假人！ 的本地化字符串。
        /// </summary>
        internal static string msg_Mask {
            get {
                return ResourceManager.GetString("msg_Mask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检测到玩家名称异常！ 的本地化字符串。
        /// </summary>
        internal static string msg_Nameless {
            get {
                return ResourceManager.GetString("msg_Nameless", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检测到玩家 {player} 使用远程终端！ 的本地化字符串。
        /// </summary>
        internal static string msg_RemoteTerminal {
            get {
                return ResourceManager.GetString("msg_RemoteTerminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检测到玩家 {player} 将飞船物品摆放到异常位置({position})！ 的本地化字符串。
        /// </summary>
        internal static string msg_ShipBuild {
            get {
                return ResourceManager.GetString("msg_ShipBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {player} 请等待飞船人数达到 {cfg} 以上再拉杆，谢谢！ 的本地化字符串。
        /// </summary>
        internal static string msg_ShipConfig2 {
            get {
                return ResourceManager.GetString("msg_ShipConfig2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {player} 请等待飞船人数达到 {player_count}({cfg4}%) 并且 游戏时间在 {cfg3} 之后起飞(当前时间:{game_time}) 的本地化字符串。
        /// </summary>
        internal static string msg_ShipConfig4 {
            get {
                return ResourceManager.GetString("msg_ShipConfig4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检测到玩家 {player} 强制拉杆！ 的本地化字符串。
        /// </summary>
        internal static string msg_ShipConfig5 {
            get {
                return ResourceManager.GetString("msg_ShipConfig5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检测到玩家 {player} 频繁使用灯光！ 的本地化字符串。
        /// </summary>
        internal static string msg_ShipLight {
            get {
                return ResourceManager.GetString("msg_ShipLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检测到玩家 {player} 频繁制造噪音！ 的本地化字符串。
        /// </summary>
        internal static string msg_ShipTerminal {
            get {
                return ResourceManager.GetString("msg_ShipTerminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检测到玩家 {player} 使用{item}对玩家 {player2} 造成异常伤害！({damageAmount}) 的本地化字符串。
        /// </summary>
        internal static string msg_Shovel {
            get {
                return ResourceManager.GetString("msg_Shovel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检测到玩家 {player} {item}范围异常，对玩家 {player2} 造成伤害！({distance},{damageAmount}) 的本地化字符串。
        /// </summary>
        internal static string msg_Shovel2 {
            get {
                return ResourceManager.GetString("msg_Shovel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检测到玩家 {player} 空手对玩家 {player2} 造成伤害！({damageAmount}) 的本地化字符串。
        /// </summary>
        internal static string msg_Shovel3 {
            get {
                return ResourceManager.GetString("msg_Shovel3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检测到玩家 {player} 使用{item}对敌人 {enemyName} 造成异常伤害！({damageAmount}) 的本地化字符串。
        /// </summary>
        internal static string msg_Shovel4 {
            get {
                return ResourceManager.GetString("msg_Shovel4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检测到玩家 {player} {item}范围异常，对敌人 {enemyName} 造成伤害！({damageAmount}) 的本地化字符串。
        /// </summary>
        internal static string msg_Shovel5 {
            get {
                return ResourceManager.GetString("msg_Shovel5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检测到玩家 {player} 空手对敌人 {enemyName} 造成伤害！({damageAmount}) 的本地化字符串。
        /// </summary>
        internal static string msg_Shovel6 {
            get {
                return ResourceManager.GetString("msg_Shovel6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;color=yellow&gt;[{player}] &lt;color=green&gt;新的生物数据已发送至终端！&lt;/color&gt;&lt;/color&gt; 的本地化字符串。
        /// </summary>
        internal static string msg_snc_player {
            get {
                return ResourceManager.GetString("msg_snc_player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检测玩家 {player} 强制激怒机枪！(距离：{Distance}) 的本地化字符串。
        /// </summary>
        internal static string msg_Turret {
            get {
                return ResourceManager.GetString("msg_Turret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检测玩家 {player} 强制激怒机枪(空手)！ 的本地化字符串。
        /// </summary>
        internal static string msg_Turret2 {
            get {
                return ResourceManager.GetString("msg_Turret2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你是房主，投票直接起飞！ 的本地化字符串。
        /// </summary>
        internal static string msg_vote {
            get {
                return ResourceManager.GetString("msg_vote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {player} 投票让飞船提前离开({now}/{max}) 的本地化字符串。
        /// </summary>
        internal static string msg_vote_player {
            get {
                return ResourceManager.GetString("msg_vote_player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;color=green&gt;欢迎 &lt;color=yellow&gt;{player}&lt;/color&gt; 加入飞船&lt;/color&gt; 的本地化字符串。
        /// </summary>
        internal static string msg_wlc_player {
            get {
                return ResourceManager.GetString("msg_wlc_player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [反作弊] 的本地化字符串。
        /// </summary>
        internal static string Prefix {
            get {
                return ResourceManager.GetString("Prefix", resourceCulture);
            }
        }
    }
}
