//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AntiCheat.Lang {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class zh_CN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal zh_CN() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AntiCheat.Lang.zh_CN", typeof(zh_CN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 召唤老板检测 的本地化字符串。
        /// </summary>
        internal static string config_Boss {
            get {
                return ResourceManager.GetString("config_Boss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发言伪造检测 的本地化字符串。
        /// </summary>
        internal static string config_ChatReal {
            get {
                return ResourceManager.GetString("config_ChatReal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 销毁物品检测 的本地化字符串。
        /// </summary>
        internal static string config_DespawnItem {
            get {
                return ResourceManager.GetString("config_DespawnItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 怪物异常检测 的本地化字符串。
        /// </summary>
        internal static string config_Enemy {
            get {
                return ResourceManager.GetString("config_Enemy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 零元购检测 的本地化字符串。
        /// </summary>
        internal static string config_FreeBuy {
            get {
                return ResourceManager.GetString("config_FreeBuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 刷礼物盒检测 的本地化字符串。
        /// </summary>
        internal static string config_Gift {
            get {
                return ResourceManager.GetString("config_Gift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 隔空取物检测 的本地化字符串。
        /// </summary>
        internal static string config_GrabObject {
            get {
                return ResourceManager.GetString("config_GrabObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 隐身检测 的本地化字符串。
        /// </summary>
        internal static string config_Invisibility {
            get {
                return ResourceManager.GetString("config_Invisibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 物品使用冷却异常检测 的本地化字符串。
        /// </summary>
        internal static string config_ItemCooldown {
            get {
                return ResourceManager.GetString("config_ItemCooldown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 喷气背包爆炸检测 的本地化字符串。
        /// </summary>
        internal static string config_Jetpack {
            get {
                return ResourceManager.GetString("config_Jetpack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检测到该行为时踢出玩家 的本地化字符串。
        /// </summary>
        internal static string config_Kick {
            get {
                return ResourceManager.GetString("config_Kick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 击杀敌人检测 的本地化字符串。
        /// </summary>
        internal static string config_KillEnemy {
            get {
                return ResourceManager.GetString("config_KillEnemy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 引爆地雷检测 的本地化字符串。
        /// </summary>
        internal static string config_Landmine {
            get {
                return ResourceManager.GetString("config_Landmine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 小地图检测 的本地化字符串。
        /// </summary>
        internal static string config_Map {
            get {
                return ResourceManager.GetString("config_Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 刷假人检测 的本地化字符串。
        /// </summary>
        internal static string config_Mask {
            get {
                return ResourceManager.GetString("config_Mask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 玩家名字检测(Nameless或Unknown) 的本地化字符串。
        /// </summary>
        internal static string config_Nameless {
            get {
                return ResourceManager.GetString("config_Nameless", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 飞船物品位置异常检测 的本地化字符串。
        /// </summary>
        internal static string config_ShipBuild {
            get {
                return ResourceManager.GetString("config_ShipBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 非房主只有在超过指定人数才能进行着陆(需要关闭房主权限) 的本地化字符串。
        /// </summary>
        internal static string config_ShipConfig2 {
            get {
                return ResourceManager.GetString("config_ShipConfig2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 非房主只有在该时间点以后才能起飞 的本地化字符串。
        /// </summary>
        internal static string config_ShipConfig3 {
            get {
                return ResourceManager.GetString("config_ShipConfig3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 非房主只有在当飞船人数(存活)超过以上比例才能起飞(0-100%) 的本地化字符串。
        /// </summary>
        internal static string config_ShipConfig4 {
            get {
                return ResourceManager.GetString("config_ShipConfig4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检测强制拉杆行为(检测到该行为时踢出玩家) 的本地化字符串。
        /// </summary>
        internal static string config_ShipConfig5 {
            get {
                return ResourceManager.GetString("config_ShipConfig5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 投票超过以上比例才能起飞(0-100%) 的本地化字符串。
        /// </summary>
        internal static string config_ShipConfig6 {
            get {
                return ResourceManager.GetString("config_ShipConfig6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 灯关秀检测 的本地化字符串。
        /// </summary>
        internal static string config_ShipLight {
            get {
                return ResourceManager.GetString("config_ShipLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 只有房主才有着陆权限 的本地化字符串。
        /// </summary>
        internal static string config_ShipSetting {
            get {
                return ResourceManager.GetString("config_ShipSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 终端噪音检测 的本地化字符串。
        /// </summary>
        internal static string config_ShipTerminal {
            get {
                return ResourceManager.GetString("config_ShipTerminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 铲子伤害检测 的本地化字符串。
        /// </summary>
        internal static string config_Shovel {
            get {
                return ResourceManager.GetString("config_Shovel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 刷蜘蛛网检测 的本地化字符串。
        /// </summary>
        internal static string config_SpawnWebTrap {
            get {
                return ResourceManager.GetString("config_SpawnWebTrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 激怒机枪检测 的本地化字符串。
        /// </summary>
        internal static string config_Turret {
            get {
                return ResourceManager.GetString("config_Turret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;color=green&gt;欢迎 &lt;color=yellow&gt;{player}&lt;/color&gt; 加入飞船&lt;/color&gt; 的本地化字符串。
        /// </summary>
        internal static string msg_wlc_player {
            get {
                return ResourceManager.GetString("msg_wlc_player", resourceCulture);
            }
        }
    }
}
